trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
  - task: richardfennellBM.BM-VSTS-PesterRunner-Task.Pester-Task.Pester@8
    displayName: 'Pester Test Runner - Network Template'
    inputs:
      scriptFolder: '@{Path=''$(System.DefaultWorkingDirectory)\tests\Test.ARMTemplate.ps1''; Parameters=@{TemplatePath =''$(System.DefaultWorkingDirectory)\azuredeploy.json''; parameters =$(hubParameters); variables = $(hubVariables); resources = $(hubResources)}}'
      resultsFile: '$(System.DefaultWorkingDirectory)\TEST-Hub-Network.xml'
	  
  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/TEST-*.xml'
    inputs:
      testResultsFormat: NUnit