trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: Pester@10
  inputs:
    scriptFolder: '@{Path=''$(System.DefaultWorkingDirectory)\tests\Test.ARMTemplate.ps1''; Parameters=@{TemplatePath =''$(System.DefaultWorkingDirectory)\azuredeploy.json''; parameters =$(parameters); variables = $(variables); functions = $(functions); resources = $(resources); outputs = $(outputs)}}'
    resultsFile: '$(System.DefaultWorkingDirectory)\TEST-Pester.XML'
    usePSCore: False

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '$(System.DefaultWorkingDirectory)\TEST-Pester.XML'
  condition: always()

