# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: richardfennellBM.BM-VSTS-PesterRunner-Task.Pester-Task.Pester@10
    displayName: 'Pester Test - Module'
    inputs:
      scriptFolder: '@{Path=''$(System.DefaultWorkingDirectory)\AzureBatch\armTemplateTest.ps1'';parameters=@{templatePath=''$(System.DefaultWorkingDirectory)\*.json''}}'
      resultsFile: '$(System.DefaultWorkingDirectory)\Test-Pester.XML'
      usePSCore: False
