trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: PublishTestResults@2
  inputs:
    scriptFolder: '@{Path=''$(System.DefaultWorkingDirectory)\tests\ARMTemplate\Test.ARMTemplate.ps1''; Parameters=@{TemplatePath =''$(System.DefaultWorkingDirectory)\azuredeploy.json''; parameters =$(parameters); variables = $(variables); functions = $(functions); resources = $(resources); outputs = $(outputs)}}'
    resultsFile: '$(System.DefaultWorkingDirectory)\TEST-ARMTemplate.XML'
    usePSCore: False