trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
  - task: richardfennellBM.BM-VSTS-PesterRunner-Task.Pester-Task.Pester@7
    displayName: 'Pester Test - Functions'
    inputs:
      scriptFolder: 'hashtable @{Path="$(System.DefaultWorkingDirectory)\tests\Test.ARMTemplate.ps1";Parameters=@{TemplatePath ='$(System.DefaultWorkingDirectory)\azuredeploy.json'
      resultsFile: '$(System.DefaultWorkingDirectory)\Test-Pester.XML'
      ForceUseOfPesterInTasks: true
    enabled: false

